### PR TITLE
add load_module and improve docs

### PR DESCRIPTION
**Pull request by timotheecour**
This PR adds `load_module` which works as follows:
```py
import monorepo
# `load_module` function will search up from the current directory for a
# file named `.monorepo_root`, which is used to determine the root directory
# it then adds (if not already there) the root to sys.path, and then calls `importlib.import_module`
mymodule2 = monorepo.load_module("pkg1.pkg2.mymodule")
mymodule2.my_function()
```
It doesn't have any of the caveats of `load_package` (module duplication, module name clashes etc) mentioned in https://github.com/myleott/monorepo/pull/4

(see discussion in https://characterorg.slack.com/archives/C02T4TKCH0D/p1704849283733079?thread_ts=1704828327.016509&cid=C02T4TKCH0D)

## note
this was the alternative I had in mind to https://github.com/myleott/monorepo/pull/3 but https://github.com/myleott/monorepo/pull/3 (ie deprecation) could've been a viable alternative (with pull/3 user would have to update their scripts to set PYTHONPATH; with this PR pull/4, the code can instead be modified to use `load_module` instead of `load_package` and users don't have to update their scripts which is less error prone)

### CODE REVIEW

**Review by myleott — APPROVED** [review]
This looks reasonable to me! Please make sure to test

**Comment by timotheecour** [comment]
tested; merging

**Comment by timotheecour** [comment]
actually I don't have write access so I can't merge

**Comment by timotheecour** [comment]
@myleott https://pypi.org/project/monorepo/ needs to be updated so `pip reinstall monorepo` will work

**Pull request merged**
